name: release.yml
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tag-release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
      - name: Refuse releasing off-main
        if: ${{ github.ref != 'refs/heads/main' || github.ref_type != 'branch' }}
        run: |
          printf "::error::Attempt to release a non-main branch\n"
          exit 1
      - name: Create release tag
        if: ${{ github.ref == 'refs/heads/main' && github.ref_type == 'branch' }}
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          set -eu
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          umask 077
          printf "${DEPLOY_KEY}" > deploy_key
          file deploy_key
          trap "rm deploy_key && echo 'gone'" EXIT
          git config user.signingKey deploy_key
          git config gpg.format ssh
          git config core.sshCommand "/usr/bin/ssh -i "$PWD/deploy_key"

          NEXT_TAG="$(.github/find-next-tag.sh)"
          git tag \
            --annotate \
            --message "Release ${NEXT_TAG} by ${{ github.triggering_actor }}" \
            --sign \
            "${NEXT_TAG}"
          git push origin "${NEXT_TAG}"
