name: release.yml
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tag-release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          fetch-tags: 'true'
      - name: Refuse releasing off-main
        if: ${{ github.ref != 'refs/heads/main' || github.ref_type != 'branch' }}
        run: |
          printf "::error::Attempt to release a non-main branch\n"
          exit 1
      - name: Create release tag
        if: ${{ github.ref == 'refs/heads/main' && github.ref_type == 'branch' }}
        env:
          DEPLOY_KEY_PEM: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          set -eu
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          DEPLOY_KEY_FILE="$(mktemp)"
          touch "${DEPLOY_KEY_FILE}"
          printf "%s\n" "${DEPLOY_KEY_PEM}" >> "${DEPLOY_KEY_FILE}"
          file "${DEPLOY_KEY_FILE}"
          trap "rm '${DEPLOY_KEY_FILE}' && echo 'gone'" EXIT
          git config user.signingKey "${DEPLOY_KEY_FILE}"
          git config gpg.format ssh

          NEXT_TAG="$(.github/find-next-tag.sh)"
          git tag \
            --annotate \
            --message "Release ${NEXT_TAG} by ${{ github.triggering_actor }}" \
            --sign \
            "${NEXT_TAG}"
          git push origin "${NEXT_TAG}"
