name: Release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
      - name: Refuse releasing off-main
        if: ${{ github.ref != 'refs/heads/main' || github.ref_type != 'branch' }}
        run: |
          printf "::error::Attempt to release a non-main branch\n"
      - name: Create release tag
        if: ${{ github.ref == 'refs/heads/main' && github.ref_type == 'branch' }}
        run: |
          set -eu
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          NEXT_TAG="$(.github/find-next-tag.sh)"
          git tag \
            --annotate \
            --message "Release ${NEXT_TAG} by ${{ github.triggering_actor }}" \
            "${NEXT_TAG}"
          git push origin "${NEXT_TAG}"
